# Generated by Django 3.2.8 on 2021-11-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
    ]
