# Generated by Django 3.2.8 on 2021-12-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='posts/thumb', verbose_name='Thumb'),
        ),
    ]
